config/routes.rb
BeerApp::Application.routes.draw do
  resources :beers

end

app/models/beer.rb
class Beer < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/beers_controller.rb
class BeersController < ApplicationController
  # GET /beers
  # GET /beers.xml
  def index
    @beers = Beer.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @beers }
    end
  end

  # GET /beers/1
  # GET /beers/1.xml
  def show
    @beer = Beer.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @beer }
    end
  end

  # GET /beers/new
  # GET /beers/new.xml
  def new
    @beer = Beer.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @beer }
    end
  end

  # GET /beers/1/edit
  def edit
    @beer = Beer.find(params[:id])
  end

  # POST /beers
  # POST /beers.xml
  def create
    @beer = Beer.new(params[:beer])

    respond_to do |format|
      if @beer.save
        format.html { redirect_to(@beer, :notice => 'Beer was successfully created.') }
        format.xml  { render :xml => @beer, :status => :created, :location => @beer }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @beer.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /beers/1
  # PUT /beers/1.xml
  def update
    @beer = Beer.find(params[:id])

    respond_to do |format|
      if @beer.update_attributes(params[:beer])
        format.html { redirect_to(@beer, :notice => 'Beer was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @beer.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /beers/1
  # DELETE /beers/1.xml
  def destroy
    @beer = Beer.find(params[:id])
    @beer.destroy

    respond_to do |format|
      format.html { redirect_to(beers_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/beers_helper.rb
module BeersHelper
end

app/views/beers/_form.html.erb
<%= form_for(@beer) do |f| %>
  <% if @beer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@beer.errors.count, "error") %> prohibited this beer from being saved:</h2>

      <ul>
      <% @beer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :beerName %><br />
    <%= f.text_field :beerName %>
  </div>
  <div class="field">
    <%= f.label :breweryName %><br />
    <%= f.text_field :breweryName %>
  </div>
  <div class="field">
    <%= f.label :breweryID %><br />
    <%= f.text_field :breweryID %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :style %><br />
    <%= f.text_field :style %>
  </div>
  <div class="field">
    <%= f.label :ibu %><br />
    <%= f.text_field :ibu %>
  </div>
  <div class="field">
    <%= f.label :abv %><br />
    <%= f.text_field :abv %>
  </div>
  <div class="field">
    <%= f.label :srmColor %><br />
    <%= f.text_field :srmColor %>
  </div>
  <div class="field">
    <%= f.label :season %><br />
    <%= f.text_field :season %>
  </div>
  <div class="field">
    <%= f.label :region %><br />
    <%= f.text_field :region %>
  </div>
  <div class="field">
    <%= f.label :mouthFeel %><br />
    <%= f.text_field :mouthFeel %>
  </div>
  <div class="field">
    <%= f.label :distribution %><br />
    <%= f.text_field :distribution %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :foodPairing %><br />
    <%= f.text_area :foodPairing %>
  </div>
  <div class="field">
    <%= f.label :picture %><br />
    <%= f.text_field :picture %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/beers/edit.html.erb
<h1>Editing beer</h1>

<%= render 'form' %>

<%= link_to 'Show', @beer %> |
<%= link_to 'Back', beers_path %>

app/views/beers/index.html.erb
<h1>Listing beers</h1>

<table>
  <tr>
    <th>Beername</th>
    <th>Breweryname</th>
    <th>Breweryid</th>
    <th>Price</th>
    <th>Style</th>
    <th>Ibu</th>
    <th>Abv</th>
    <th>Srmcolor</th>
    <th>Season</th>
    <th>Region</th>
    <th>Mouthfeel</th>
    <th>Distribution</th>
    <th>Description</th>
    <th>Foodpairing</th>
    <th>Picture</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @beers.each do |beer| %>
  <tr>
    <td><%= beer.beerName %></td>
    <td><%= beer.breweryName %></td>
    <td><%= beer.breweryID %></td>
    <td><%= beer.price %></td>
    <td><%= beer.style %></td>
    <td><%= beer.ibu %></td>
    <td><%= beer.abv %></td>
    <td><%= beer.srmColor %></td>
    <td><%= beer.season %></td>
    <td><%= beer.region %></td>
    <td><%= beer.mouthFeel %></td>
    <td><%= beer.distribution %></td>
    <td><%= beer.description %></td>
    <td><%= beer.foodPairing %></td>
    <td><%= beer.picture %></td>
    <td><%= link_to 'Show', beer %></td>
    <td><%= link_to 'Edit', edit_beer_path(beer) %></td>
    <td><%= link_to 'Destroy', beer, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Beer', new_beer_path %>

app/views/beers/new.html.erb
<h1>New beer</h1>

<%= render 'form' %>

<%= link_to 'Back', beers_path %>

app/views/beers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Beername:</b>
  <%= @beer.beerName %>
</p>

<p>
  <b>Breweryname:</b>
  <%= @beer.breweryName %>
</p>

<p>
  <b>Breweryid:</b>
  <%= @beer.breweryID %>
</p>

<p>
  <b>Price:</b>
  <%= @beer.price %>
</p>

<p>
  <b>Style:</b>
  <%= @beer.style %>
</p>

<p>
  <b>Ibu:</b>
  <%= @beer.ibu %>
</p>

<p>
  <b>Abv:</b>
  <%= @beer.abv %>
</p>

<p>
  <b>Srmcolor:</b>
  <%= @beer.srmColor %>
</p>

<p>
  <b>Season:</b>
  <%= @beer.season %>
</p>

<p>
  <b>Region:</b>
  <%= @beer.region %>
</p>

<p>
  <b>Mouthfeel:</b>
  <%= @beer.mouthFeel %>
</p>

<p>
  <b>Distribution:</b>
  <%= @beer.distribution %>
</p>

<p>
  <b>Description:</b>
  <%= @beer.description %>
</p>

<p>
  <b>Foodpairing:</b>
  <%= @beer.foodPairing %>
</p>

<p>
  <b>Picture:</b>
  <%= @beer.picture %>
</p>


<%= link_to 'Edit', edit_beer_path(@beer) %> |
<%= link_to 'Back', beers_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BeerApp</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>